# Generated by Django 3.2.9 on 2021-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'stores',
                'managed': True,
            },
        ),
    ]
